name: Deploy to Firebase

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g firebase-tools
      - run: npm ci
        working-directory: ./hosting
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BAILEYMENDEL_FIREBASE }}
      - run: firebase experiments:enable webframeworks
      - run: firebase deploy
