name: Deploy to Firebase
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g firebase-tools
      - run: echo {{ secrets.FIREBASE_SERVICE_ACCOUNT_BAILEYMENDEL_FIREBASE }} > key.json
      - run: firebase deploy
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: "key.json"
